fix(program.cs): using namespace
##[error]Program.cs(16,30): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/HelloWorld/HelloWorld/GradeBook.csproj]